import type { Metadata } from 'next';
import { Inter, Montserrat } from 'next/font/google';
import localFont from 'next/font/local';
import { Header } from '../shared/components/Header';
import { Footer } from '../shared/components/Footer';
import './globals.css';

export const metadata: Metadata = {
	title: 'VASIA_PUPKI PHOTOGRAPHY',
	description: 'Generated by create next app',
};
const inter = Inter({
	subsets: ['latin', 'cyrillic'],
	variable: '--font-inter',
	weight: ['100', '200', '300', '400', '500', '700'],
	display: 'swap',
});

const montserrat = Montserrat({
	subsets: ['latin', 'cyrillic'],
	variable: '--font-montserrat',
	weight: ['200', '300', '400', '500', '700'],
	display: 'swap',
 
});

const clashDisplay = localFont({
	src: [
		{
			path: './fonts/ClashDisplay-Variable.woff2',
			style: 'normal',
			weight: '100 900', // диапазон variable-font
		},
	],
	declarations: [
		{
			prop: 'unicode-range',
			value:
				'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
		},
	],
	variable: '--font-clash-display',
});
const satoshi = localFont({
	src: [
		{
			path: './fonts/Satoshi-Variable.woff2',
			style: 'normal',
			weight: '100 900', // диапазон variable-font
		},
	],
	variable: '--font-satoshi',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='dark'>
			<body
				className={`${clashDisplay.variable} ${satoshi.variable} ${inter.variable} ${montserrat.variable} scrollBar  antialiased`}>
				<Header />
				{children}
				<Footer />
				<div
					id='cursor-custom'
					className='fixed  top-0 left-0 w-14.5 h-14.5 pointer-events-none  opacity-0 z-9999'>
					<div className='custom-text body1 uppercase absolute top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2' />
					<div className='absolute top-0 left-0'>
						<span className='block w-2 h-px absolute top-0 left-0 bg-white'></span>
						<span className='block w-px h-2 absolute top-0 left-0 bg-white'></span>
					</div>
					<div className='absolute bottom-0 left-0'>
						<span className='block w-px h-2 absolute bottom-0 left-0 bg-white'></span>
						<span className='block w-2 h-px absolute bottom-0 left-0 bg-white'></span>
					</div>
					<div className='absolute bottom-0 right-0'>
						<span className='block w-px h-2 absolute bg-white bottom-0 right-0'></span>
						<span className='block w-2 h-px absolute bg-white bottom-0 right-0'></span>
					</div>
					<div className='absolute top-0 right-0'>
						<span className='block w-px h-2 absolute top-0 right-0 bg-white'></span>
						<span className='block w-2 h-px absolute top-0 right-0 bg-white'></span>
					</div>
				</div>
			</body>
		</html>
	);
}
