import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import { Header } from '../shared/components/Header';
import './globals.css';
import { useInertialScroll } from './useInertialScroll';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
	weight: ['100', '200', '300', '400', '500', '700'],
	display: 'swap',
});

const clashDisplay = localFont({
	src: [
		{
			path: './fonts/ClashDisplay-Variable.woff2',
			style: 'normal',
			weight: '100 900', // диапазон variable-font
		},
	],
	variable: '--font-clash-display',
});
const satoshi = localFont({
	src: [
		{
			path: './fonts/Satoshi-Variable.woff2',
			style: 'normal',
			weight: '100 900', // диапазон variable-font
		},
	],
	variable: '--font-satoshi',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='dark'>
			<body
				className={`${clashDisplay.variable} ${satoshi.variable} ${inter.variable}   antialiased`}>
				<Header />
				{children}
				<div
					id='cursor-custom'
					className='fixed  top-0 left-0 w-14.5 h-14.5 pointer-events-none  opacity-0 z-9999'>
					<div className='body1 uppercase absolute top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2'>
						view
					</div>
					<div className='absolute top-0 left-0'>
						<span className='block w-2 h-px absolute top-0 left-0 bg-white'></span>
						<span className='block w-px h-2 absolute top-0 left-0 bg-white'></span>
					</div>
					<div className='absolute bottom-0 left-0'>
						<span className='block w-px h-2 absolute bottom-0 left-0 bg-white'></span>
						<span className='block w-2 h-px absolute bottom-0 left-0 bg-white'></span>
					</div>
					<div className='absolute bottom-0 right-0'>
						<span className='block w-px h-2 absolute bg-white bottom-0 right-0'></span>
						<span className='block w-2 h-px absolute bg-white bottom-0 right-0'></span>
					</div>
					<div className='absolute top-0 right-0'>
						<span className='block w-px h-2 absolute top-0 right-0 bg-white'></span>
						<span className='block w-2 h-px absolute top-0 right-0 bg-white'></span>
					</div>
				</div>
			</body>
		</html>
	);
}
