/**
 * Все подписи интерфейса (заголовки секций, кнопки, состояния).
 * Контент фотографа сюда не относится — он хранится в БД.
 * Для RU/EN достаточно будет завести такой же объект на английском и выбирать по локали.
 */
export const texts = {
	common: {
		loading: 'Загрузка…',
		photographer: 'фотограф',
		contactMe: 'Связаться со мной',
		allReviews: 'Все отзывы',
		allArticles: 'Все статьи',
		allAlbums: 'Все альбомы',
		toggleTheme: 'Переключить тему',
		videoPlayer: 'Видео',
		close: 'Закрыть',
		loadError: 'Не удалось загрузить данные. Попробуйте обновить страницу.',
	},
	notFound: {
		title: 'Страница не найдена',
		text: 'Возможно, она была удалена или вы перешли по неверной ссылке.',
		toHome: 'На главную',
	},
	error: {
		title: 'Что-то пошло не так',
		text: 'Попробуйте обновить страницу. Если ошибка повторится — напишите мне.',
		retry: 'Попробовать снова',
	},
	cursor: {
		read: 'читать',
		open: 'открыть',
	},
	nav: {
		home: 'Главная',
		about: 'Обо мне',
		works: 'Работы',
		reviews: 'Отзывы',
		blogs: 'Блоги',
		contacts: 'Контакты',
	},
	scrollIndicator: {
		scroll: 'Листайте',
		cooperate: 'Сотрудничайте со мной',
	},
	footer: {
		writeMe: 'Напишите мне',
	},
	home: {
		aboutTitle: 'Обо мне ...',
		moreAboutMe: 'Ещё обо мне',
		brandsTitle: 'Бренды, с которыми я работал',
		albumsTitle: 'Альбомы',
		expertiseTitle: 'Мои направления',
		expertiseMoreTitle: 'Подождите…',
		expertiseMoreSubtitle: 'И это ещё не всё!',
		reviewsTitleSmall: 'Радость и истории от',
		reviewsTitleLarge: 'Моих Клиентов',
		articlesTitleSmall: 'Вдохновляйтесь моими',
		articlesTitleLarge: 'Статьями',
		faqTitle: 'Частые вопросы',
		faqSubtitle: 'Все ответы здесь',
	},
	about: {
		qualitiesTitle: 'Что вы найдёте во мне',
		awardsTitleSmall: 'Моменты признания',
		awardsTitleLarge: 'Мои награды',
		gearTitle: 'Моя техника',
	},
	works: {
		photos: 'Фото',
		videos: 'Видео',
		albumsTitle: 'Альбомы',
		albumsEmpty: 'Альбомы не найдены',
		albumNotFound: 'Альбом не найден',
		moreAlbums: 'Ещё альбомы',
		orderPrints: 'Заказать печать',
		videosTitle: 'Видео',
		videosEmpty: 'Видео не найдены',
	},
	reviews: {
		title: 'Отзывы',
		empty: 'Отзывов пока нет',
		error: 'Не удалось загрузить отзывы',
	},
	blogs: {
		title: 'Блоги',
		empty: 'Статей пока нет',
		notFound: 'Статья не найдена',
		notFoundHint: 'Возможно, она была удалена или ссылка устарела.',
		category: 'Категория:',
		readAlso: 'Читайте также',
	},
	contacts: {
		title: 'Контакты',
		email: 'Email',
		phone: 'Телефон',
		formTitle: 'Напишите мне',
		name: 'Имя',
		message: 'Ваше сообщение',
		submit: 'Отправить',
		sending: 'Отправка…',
		needContact: 'Укажите email или телефон, чтобы я мог с вами связаться',
		sendError: 'Не удалось отправить заявку, попробуйте ещё раз',
		successTitle: 'Спасибо! Заявка отправлена.',
		successText: 'Я свяжусь с вами в ближайшее время.',
		sendAnother: 'Отправить ещё одну',
	},
};
