export const QueryKeys = {
	blogs: (id: string) => ['blogs', id],
	blog: (id: string) => ['blog', id],
	albums: () => ['albums'],
	album: (id: string) => ['album', id],
	videos: () => ['videos'],
	brands: () => ['brands'],
	expertise: () => ['expertise'],
	reviews: () => ['reviews'],
	socials: () => ['socials'],
	settings: () => ['settings'],
	stats: () => ['stats'],
	faq: () => ['faq'],
	awards: () => ['awards'],
	gear: () => ['gear'],
	qualities: () => ['qualities'],
};
